[project]
name = "goit-pycore-hw-08"
version = "0.1.0"
description = ""
authors = [
    {name = "nikkahl", email = "galtveronika1@gmail.com"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"